modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "rage"
version = "${version}"
displayName = "Rage"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''

[[dependencies.rage]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
