modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "rage"
version = "${version}"
displayName = "Rage"
authors = "MineAqcs"
description = '''
Add Rage to entities. Inspired by aoqi.100bt.com
'''

[[dependencies.rage]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
